#!/bin/sh
# Description: An easy to use firewall builder for computers using dual nics or just one

prefix="."
option="$1"

usage()
{
	SCRIPT_DIR=$(dirname "$(realpath "$0")")
	cat  <<EOF
Usage: $(basename $0)
iptables wrapper for restrictive setups
	Usage: $(basename $0)  file...
	Usage: $(basename $0)  OPTION
OPTION
	-h	print this help message

PLUGINS
$(ls "$SCRIPT_DIR/../share/harmony/plugins" | sed 's/^/\t/g')

EOF
	exit 1
}

load_plugin()
{
	SCRIPT_DIR=$(dirname "$(realpath "$0")")
	source "$SCRIPT_DIR/../share/harmony/plugins/$1"
}

case $option in
	*.conf) source "$1";;
	-) tmpfile=$(mktemp); cat > "$tmpfile"; source "$tmpfile"; rm -f "$tmpfile";;
	-h|--help|*) usage;;

esac

