#!/bin/sh
# Description: An easy to use firewall builder for computers using dual nics or just one

prefix="."

script_dir=$(realpath "$0")
script_dir="${script_dir%/*}"

name="${0##*/}"

usage()
{
	echo "Usage: $name [OPTION] [FILE...]
iptables wrapper for restrictive setups

OPTION
	-h, --help	print this help message
	-v, --verbose	echo each file name as it is being parsed

PLUGINS
$(ls "$script_dir/../share/harmony/plugins" | sed 's/^/\t/g')
"
	exit 1
}

load_plugin()
{
	source "$script_dir/../share/harmony/plugins/$1"
}

[[ $# == 0 ]] && usage

for arg in $@; do
	case $arg in
		*.conf) [[ "$v" ]] && echo "$arg"
			source "$arg";;
		-) tmpfile=$(mktemp); cat > "$tmpfile"; source "$tmpfile"; rm -f "$tmpfile";;
		-f|--fast) f=1; [[ $# == 1 ]] && usage;;
		-v|--verbose) v=1; [[ $# == 1 ]] && usage;;
		*) plugin="$script_dir/../share/harmony/plugins/$arg"; shift; [[ -f "$plugin" ]] && source "$plugin" "$@" || usage;;
		-h|--help) usage;;

	esac
done
