#!/bin/sh
# Description: anti dos and anti nmap


# TODO: find subnet for spoofed packetes section
anti_dos_iptables()
{
	# Use an iface that is WAN facing
	iface="${1}"

	# https://javapipe.com/iptables-ddos-protection
	### 1: Drop invalid packets ###
	iptables -t mangle -A PREROUTING -m conntrack --ctstate INVALID -j DROP

	### 2: Drop TCP packets that are new and are not SYN ###
	iptables -t mangle -A PREROUTING -p tcp ! --syn -m conntrack --ctstate NEW -j DROP

	### 3: Drop SYN packets with suspicious MSS value ###
	iptables -t mangle -A PREROUTING -p tcp -m conntrack --ctstate NEW -m tcpmss ! --mss 536:65535 -j DROP

	### 4: Block packets with bogus TCP flags ###
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags FIN,SYN,RST,PSH,ACK,URG NONE -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags FIN,SYN FIN,SYN -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags SYN,RST SYN,RST -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags SYN,FIN SYN,FIN -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags FIN,RST FIN,RST -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags FIN,ACK FIN -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags ACK,URG URG -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags ACK,FIN FIN -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags ACK,PSH PSH -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags ALL ALL -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags ALL NONE -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags ALL FIN,PSH,URG -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags ALL SYN,FIN,PSH,URG -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags ALL SYN,RST,ACK,FIN,URG -j DROP

	### 5: Block spoofed packets ###
	# As a precaution
	if [ ! -z ${iface} ]; then
		iptables -t mangle -A PREROUTING -i ${iface} -s 224.0.0.0/3 -j DROP
		iptables -t mangle -A PREROUTING -i ${iface} -s 169.254.0.0/16 -j DROP
		iptables -t mangle -A PREROUTING -i ${iface} -s 172.16.0.0/12 -j DROP
		iptables -t mangle -A PREROUTING -i ${iface} -s 192.0.2.0/24 -j DROP
		iptables -t mangle -A PREROUTING -i ${iface} -s 192.168.0.0/16 -j DROP
		iptables -t mangle -A PREROUTING -i ${iface} -s 10.0.0.0/8 -j DROP
		iptables -t mangle -A PREROUTING -i ${iface} -s 0.0.0.0/8 -j DROP
		iptables -t mangle -A PREROUTING -i ${iface} -s 240.0.0.0/5 -j DROP
		iptables -t mangle -A PREROUTING -i ${iface} -s 127.0.0.0/8 -j DROP
	fi

	### 6: Drop ICMP (you usually don't need this protocol) ###
	iptables -t mangle -A PREROUTING -p icmp -j DROP

	### 7: Drop fragments in all chains ###
	iptables -t mangle -A PREROUTING -f -j DROP

	### 8: Limit connections per source IP ###
	iptables -A INPUT -p tcp -m connlimit --connlimit-above 111 -j REJECT --reject-with tcp-reset

	### 9: Limit RST packets ###
	iptables -A INPUT -p tcp --tcp-flags RST RST -m limit --limit 2/s --limit-burst 2 -j ACCEPT
	iptables -A INPUT -p tcp --tcp-flags RST RST -j DROP

	### 10: Limit new TCP connections per second per source IP ###
	iptables -A INPUT -p tcp -m conntrack --ctstate NEW -m limit --limit 60/s --limit-burst 20 -j ACCEPT
	iptables -A INPUT -p tcp -m conntrack --ctstate NEW -j DROP

	### 11: Use SYNPROXY on all ports (disables connection limiting rule) ###
	#iptables -t raw -A PREROUTING -p tcp -m tcp --syn -j CT --notrack
	#iptables -A INPUT -p tcp -m tcp -m conntrack --ctstate INVALID,UNTRACKED -j SYNPROXY --sack-perm --timestamp --wscale 7 --mss 1460
	#iptables -A INPUT -m conntrack --ctstate INVALID -j DROP

	### Protection against port scanning ###
	if [[ ! $(iptables -nL "port-scanning" 2>/dev/null) ]]; then
		iptables -N port-scanning
		iptables -A port-scanning -p tcp --tcp-flags SYN,ACK,FIN,RST RST -m limit --limit 1/s --limit-burst 2 -j RETURN
		iptables -A port-scanning -j DROP
	fi
}




anti_dos() {

	f
