#!/bin/bash

# Description: plugin for dnscrypt-proxy

# Change this if needed to be if planning on using dnscrypt-proxy in your setup
DNSCRYPT_RESOLVERS="/usr/share/dnscrypt-proxy/dnscrypt-resolvers.csv"

# Some routines to help speed up loading config files
# Since these are static we dont need to load the rules every time, just once
DNSCRYPT_1() {

	### To do any kind of 'url'/'host' filtering you must have a working dns ###
	if [[ -f ${DNSCRYPT_RESOLVERS} && $(which dnscrypt-proxy 2>/dev/null) && ! $(iptables -nL "OUT_DNSCRYPT_ACL" 2>/dev/null) ]]; then
		iptables -N IN_DNSCRYPT_ACL
		iptables -N OUT_DNSCRYPT_ACL

		IFACE=$(netstat -rnf iface 2>&1 |  sed -e "s/[[:space:]]\+/ /g" | grep UG | cut -d " " -f8)
		IFACE_IP="$(ip address show ${IFACE} | grep -oP '(?<=inet ).*(?=/)')"

		for dns_host in $(egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' ${DNSCRYPT_RESOLVERS} | cut -d "," -f1); do

			if [[ ${dns_host} == *:* ]]; then
				HOST_IP=$(echo "${dns_host}"   | cut -d ":" -f1)
				HOST_PORT=$(echo "${dns_host}" | cut -d ":" -f2)
			else
				HOST_IP="${dns_host}"
				HOST_PORT=443
			fi
			# TCP
			iptables -A OUT_DNSCRYPT_ACL -o ${IFACE} -p tcp --dport ${HOST_PORT} -s ${IFACE_IP} -d ${HOST_IP} -m owner --uid-owner dnscrypt -m owner --gid-owner dnscrypt -m state --state NEW,ESTABLISHED -j ACCEPT
			iptables -A IN_DNSCRYPT_ACL -i ${IFACE} -p tcp --sport ${HOST_PORT} -d ${IFACE_IP} -s ${HOST_IP} -m state --state ESTABLISHED -j ACCEPT
			# UDP
			#iptables -A OUT_DNSCRYPT_ACL -o ${IFACE} -p udp --dport ${HOST_PORT} -s ${IFACE_IP} -d ${HOST_IP} -m owner --uid-owner dnscrypt -m owner --gid-owner dnscrypt -m state --state NEW,ESTABLISHED -j ACCEPT
			iptables -A OUT_DNSCRYPT_ACL -o ${IFACE} -p udp --dport ${HOST_PORT} -s ${IFACE_IP} -d ${HOST_IP} -m state --state NEW,ESTABLISHED -j ACCEPT
			iptables -A IN_DNSCRYPT_ACL -i ${IFACE} -p udp --sport ${HOST_PORT} -d ${IFACE_IP} -s ${HOST_IP} -m state --state ESTABLISHED -j ACCEPT

		done
	fi
}

DNSCRYPT_2() {



}
