#!/bin/bash
# Description: plugin for iptables
# Dependencies: iptables
flush()
{
	iptables -F
	iptables -X
	iptables -t filter -F
	iptables -t filter -X
	iptables -t mangle -F
	iptables -t mangle -X
	iptables -t nat -F
	iptables -t nat -X
	iptables -t raw -F
	iptables -t raw -X

	# Default Policies
	iptables -P INPUT DROP
	iptables -P OUTPUT DROP
	iptables -P FORWARD DROP
}

# -----------------------------------------------------------------------------
# Function: prerouting_security
# Argument: $1 - WAN interface name (e.g., eth0)
#
# Description:
#   This function applies a series of iptables rules designed to harden the
#   network stack against malformed packets, spoofing, scanning, and simple
#   DDoS techniques. It mostly operates in the 'mangle' table at the PREROUTING
#   chain and includes additional INPUT chain protections.
#
#   If a WAN interface is specified, spoofed source IP ranges will be blocked
#   only on that interface.
#
# Rules Implemented:
#   1. Drop invalid connection states
#   2. Drop new TCP packets without SYN
#   3. Drop SYN packets with abnormal MSS values
#   4. Block various malformed TCP flag combinations
#   5. Drop spoofed source IP ranges on specified WAN interface
#   6. Drop all ICMP traffic (optional; may break ping or diagnostics)
#   7. Drop fragmented packets
#   8. Limit the number of connections per source IP
#   9. Limit RST packets to mitigate RST flood attacks
#  10. Limit rate of new TCP connections
#  11. (Optional) Enable SYNPROXY for full TCP handshake protection
#  12. Create a custom 'port-scanning' chain to detect and limit port scans
#
# Note:
#   - Some sections are commented out for optional use (e.g., SYNPROXY).
#   - Make sure iptables modules are loaded (e.g., conntrack, tcpmss).
# -----------------------------------------------------------------------------
prerouting_security()
{
	local wan="$1"

	# https://javapipe.com/iptables-ddos-protection
	# Drop invalid packets
	iptables -t mangle -A PREROUTING -m conntrack --ctstate INVALID -j DROP

	# Drop TCP packets that are new and are not SYN
	iptables -t mangle -A PREROUTING -p tcp ! --syn -m conntrack --ctstate NEW -j DROP

	# Drop SYN packets with suspicious MSS value
	iptables -t mangle -A PREROUTING -p tcp -m conntrack --ctstate NEW -m tcpmss ! --mss 536:65535 -j DROP

	# Block packets with bogus TCP flags
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags FIN,SYN,RST,PSH,ACK,URG NONE -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags FIN,SYN FIN,SYN -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags SYN,RST SYN,RST -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags SYN,FIN SYN,FIN -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags FIN,RST FIN,RST -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags FIN,ACK FIN -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags ACK,URG URG -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags ACK,FIN FIN -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags ACK,PSH PSH -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags ALL ALL -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags ALL NONE -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags ALL FIN,PSH,URG -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags ALL SYN,FIN,PSH,URG -j DROP
	iptables -t mangle -A PREROUTING -p tcp --tcp-flags ALL SYN,RST,ACK,FIN,URG -j DROP

	# Block spoofed packets
	if [[ ! -z $wan ]]; then
		iptables -t mangle -A PREROUTING -i $wan -s 224.0.0.0/3 -j DROP
		iptables -t mangle -A PREROUTING -i $wan -s 169.254.0.0/16 -j DROP
		iptables -t mangle -A PREROUTING -i $wan -s 172.16.0.0/12 -j DROP
		iptables -t mangle -A PREROUTING -i $wan -s 192.0.2.0/24 -j DROP
		iptables -t mangle -A PREROUTING -i $wan -s 192.168.0.0/16 -j DROP
		iptables -t mangle -A PREROUTING -i $wan -s 10.0.0.0/8 -j DROP
		iptables -t mangle -A PREROUTING -i $wan -s 0.0.0.0/8 -j DROP
		iptables -t mangle -A PREROUTING -i $wan -s 240.0.0.0/5 -j DROP
		iptables -t mangle -A PREROUTING -i $wan -s 127.0.0.0/8 -j DROP
	fi
	# Drop ICMP (you usually don't need this protocol)
	iptables -t mangle -A PREROUTING -p icmp -j DROP

	# Drop fragments in all chains
	iptables -t mangle -A PREROUTING -f -j DROP

	# Limit connections per source ip
	iptables -A INPUT -p tcp -m connlimit --connlimit-above 111 -j REJECT --reject-with tcp-reset

	# Limit RST packets
	iptables -A INPUT -p tcp --tcp-flags RST RST -m limit --limit 2/s --limit-burst 2 -j ACCEPT
	iptables -A INPUT -p tcp --tcp-flags RST RST -j DROP

	# Limit new TCP connections per second per source ip
	iptables -A INPUT -p tcp -m conntrack --ctstate NEW -m limit --limit 60/s --limit-burst 20 -j ACCEPT
	iptables -A INPUT -p tcp -m conntrack --ctstate NEW -j DROP

	# Use SYNPROXY on all ports (disables connection limiting rule)
	#iptables -t raw -A PREROUTING -p tcp -m tcp --syn -j CT --notrack
	#iptables -A INPUT -p tcp -m tcp -m conntrack --ctstate INVALID,UNTRACKED -j SYNPROXY --sack-perm --timestamp --wscale 7 --mss 1460
	#iptables -A INPUT -m conntrack --ctstate INVALID -j DROP

	# Protection against port scanning
	if [[ ! $(iptables -nL "port-scanning" 2>/dev/null) ]]; then
		iptables -N port-scanning
		iptables -A port-scanning -p tcp --tcp-flags SYN,ACK,FIN,RST RST -m limit --limit 1/s --limit-burst 2 -j RETURN
		iptables -A port-scanning -j DROP
	fi

	#iptables -A OUTPUT -m tcp -p tcp --tcp-flags ALL ACK -j ACCEPT
}

# -----------------------------------------------------------------------------
# Function: port_knocking
#
# Arguments:
#   $1 - `name` - A custom identifier for the knocking sequence, used to create
#         a unique name for the chain and the recent list to track the knock.
#   $2 - `dst_port` - The destination port where the final "knock" should land.
#   $3+ - `combo` - An array of ports that represent the port knocking sequence.
#
# Description:
#   This function sets up a port knocking sequence using iptables to secure access
#   to a specific destination port. The function works by requiring a series of
#   TCP connections to a series of ports in a specific order, and if the correct
#   sequence is knocked, access to the destination port is allowed.
#
# The function works as follows:
#   1. A new chain is created for the port knocking sequence, named after the
#      `name` argument and the destination port (`dst_port`).
#   2. The first rule ensures that the initial knock on the destination port (`dst_port`)
#      is checked against a "recent" list to see if it's part of a valid knock sequence.
#      If a valid recent connection exists within 30 seconds, access is allowed.
#   3. Each subsequent knock in the sequence is checked to ensure that it follows the
#      correct order. If a valid knock is detected, the next knock is registered.
#   4. The function also sets up an "input" chain for each knock, managing the state of
#      each port knock and validating its position in the sequence.
#   5. Once the sequence is completed, the port specified by `dst_port` is allowed.
#   6. Rules for handling established and related connections are also applied.
#
# -----------------------------------------------------------------------------
port_knocking()
{
	name="$1"
	dst_port="$2"
	shift 2
	combo=("$@")

	chain="KNOCK_${name^^}_$dst_port"
	array=( )

	iptables -N $chain
	iptables -A $chain -m state --state NEW -m tcp -p tcp --dport $dst_port -m recent --rcheck --seconds 30 --name ${name^^}${dst_port}_$# -j ACCEPT
	iptables -A $chain -m state --state NEW -m tcp -p tcp -m recent --name ${name^^}${dst_port}_$# --remove -j DROP

	i=$#
	while (( i-- > 1 )); do
		iptables -N ${chain}_INPUT_$i
		iptables -A $chain -m state --state NEW -m tcp -p tcp --dport "${combo[i]}" -m recent --rcheck --name ${name^^}${dst_port}_$i -j ${chain}_INPUT_$i
		iptables -A $chain -m state --state NEW -m tcp -p tcp -m recent --name ${name^^}${dst_port}_$i --remove -j DROP
		array+=($i)

	done

	iptables -A $chain -m state --state NEW -m tcp -p tcp --dport ${combo[0]} -m recent --name ${name^^}${dst_port}_1 --set -j DROP
	iptables -A $chain -m state --state ESTABLISHED,RELATED -j ACCEPT
        iptables -A OUTPUT -p tcp --sport $dst_port -m state --state ESTABLISHED,RELATED -j ACCEPT

	for j in "${array[@]}"; do
		iptables -A ${chain}_INPUT_$j -m recent --name ${name^^}${dst_port}_$((j+1)) --set -j DROP
	done

	iptables -A INPUT -j $chain
}

# Use only if diagnosing connection issues on the loopback interface!
default_lo()
{
	iptables -A INPUT  -i lo -s 127.0.0.1/8 -d 127.0.0.1/8 -j ACCEPT
	iptables -A OUTPUT -o lo -d 127.0.0.1/8 -s 127.0.0.1/8 -j ACCEPT
}

#acl_DNS()
#{
#	if [ ! -d $(dirname "$DNS_FILE") ]; then
#		mkdir -p $(dirname "$DNS_FILE"
#}

# This allows connections to servers from any interface
input()
{
	local iface="$1"
	local ip="$2"
	local port="$3"
	local protocol="$4"
	local IFS=' 	
'

	if [ ! -z "$5" ]; then
		local mac="-m mac --mac-source $5"
	fi

	for interface in $iface; do
		# Allows multiple ifaces to be specified as long as you use the ip like eth0:192.168.1.2
		if [[ $ip == *':'* ]]; then
			local input_iface="${ip%%:*}"
			local input_ip="${ip#*:}"
		else
			local input_iface="$interface"
			local input_ip="$ip"
		fi

		if [[ $interface =~ [0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3} ]]; then
			local iface_ip="$interface"
			local interface="$input_iface"
		else
			local iface_ip="$(ip address show $interface | grep -oP '(?<=inet ).*(?=/)' | cut -d " " -f1)"
		fi

		if [[ $input_iface == $interface ]]; then

			_filter_rules+="-A INPUT  -i $interface -p $protocol --dport $port -s $input_ip -d $iface_ip $mac -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT"$'\n'
			_filter_rules+="-A OUTPUT -o $interface -p $protocol --sport $port -d $input_ip -s $iface_ip -m state --state ESTABLISHED,RELATED -j ACCEPT"$'\n'
		fi
	done
}

# This allows the router to connect to other servers from any interface
output()
{
	local iface="$1"
	local ip="$2"
	local port="$3"
	local protocol="$4"
	local IFS=' 	
'
	if [ ! -z "$5" ]; then
		local mac="-m mac --mac-source $5"
	fi

	for interface in $iface; do
		# Allows multiple ifaces to be specified as long as you use the ip like eth0:192.168.1.2
		if [[ $ip == *':'* ]]; then
			local output_iface="${ip%%:*}"
			local output_ip="${ip#*:}"
		else
			local output_iface="$interface"
			local output_ip="$ip"
		fi


		if [[ $interface =~ [0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3} ]]; then
			local iface_ip=$interface
			local interface=$output_iface
		else
			local iface_ip="$(ip address show $interface | grep -oP '(?<=inet ).*(?=/)' | cut -d " " -f1)"
		fi


		if [[ $output_iface == $interface ]]; then

			_filter_rules+="-A INPUT  -i $interface -p $protocol --sport $port -s $output_ip -d $iface_ip $mac -m state --state ESTABLISHED,RELATED -j ACCEPT"$'\n'
			_filter_rules+="-A OUTPUT -o $interface -p $protocol --dport $port -d $output_ip -s $iface_ip -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT"$'\n'

		fi
	done
}

# This allows lan clients to use the internet
forward()
{
	local src_iface="$1"
	local src_ip="$2"
	local dst_iface="$3"
	local dst_ip="$4"
	local dst_port="$5"
	local protocol="$6"
	local IFS=' 	
'
	if [ ! -z "$7" ]; then
		local mac="-m mac --mac-source $7"
	fi

	for interface in $src_iface; do
		# Allows multiple ifaces to be specified as long as you use the ip like eth0:192.168.1.2
		if [[ $src_ip == *':'* ]]; then
			local src_iface_1="${ip%%:*}"
			local src_ip_1="${ip#*:}"
		else
			local src_iface_1="$interface"
			local src_ip_1="$src_ip"
		fi

		if [[ $src_iface_1 == $interface ]]; then
			_filter_rules+="-A FORWARD -i $src_iface_1 -p $protocol -m $protocol --dport $dst_port -s $src_ip_1 -d $dst_ip $mac -j ACCEPT"$'\n'
			_filter_rules+="-A FORWARD -i $dst_iface   -p $protocol -m $protocol --sport $dst_port -d $src_ip_1 -s $dst_ip -j ACCEPT"$'\n'
			#iptables -t nat -A POSTROUTING -o $dst_iface -j MASQUERADE
			_nat_rules+="-A POSTROUTING -o $dst_iface -p $protocol -m $protocol --dport $dst_port -s $src_ip_1 -d $dst_ip -j MASQUERADE"$'\n'
			_nat_rules+="-A POSTROUTING -o $dst_iface -p $protocol -m $protocol --sport $dst_port -d $src_ip_1 -s $dst_ip -j MASQUERADE"$'\n'
		fi
	done
}

# This allows which user and group can connect to what service
acl()
{
	local iface="$1"
	#[[ "$2" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}(/([0-9]|[12][0-9]|3[0-2]))?$ ]] && local ip="$2" || local ip="$(getent ahosts $2 | awk '{print $1}' | sort -u | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')"
	#[[ "$3" =~ ^[0-9]+(:[0-9]+)?$ ]] && local port="$3" || port="$(getent services $3 | awk '{split($2, a, "/"); print a[1]}')"
	local ip="$2"
	local port="$3"
	local user_group="$4"
	local protocol="$5"
	local IFS=' 	
'
	for interface in $iface; do
		# Allows multiple ifaces to be specified as long as you use the ip like eth0:192.168.1.2
		if [[ $ip == *':'* ]]; then
			local acl_iface="${ip%%:*}"
			local acl_ip="${ip#*:}"
		else
			local acl_iface="$interface"
			local acl_ip="$ip"
		fi

		if [[ $acl_iface == $interface ]]; then

			if [[ $interface == *':'* ]]; then
				local interface="${interface%%:*}"
				local iface_ip="${acl_iface#*:}"
			else
				local iface_ip="$(ip address show $interface | grep -oP '(?<=inet ).*(?=/)' | cut -d " " -f1)"
			fi

			local user="${user_group%%:*}"
			local group="${user_group#*:}"


			if [ ! -z $user ]; then
				user="-m owner --uid-owner $user"
			fi

			if [ ! -z $group ]; then
				group="-m owner --gid-owner $group"
			fi

			for host in $acl_ip; do
				_filter_rules+="-A OUTPUT -o $interface -p $protocol -m $protocol --dport $port -s $iface_ip -d $host $user $group -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT"$'\n'
				_filter_rules+="-A INPUT  -i $interface -p $protocol -m $protocol --sport $port -d $iface_ip -s $host -m state --state ESTABLISHED,RELATED -j ACCEPT"$'\n'
			done
		fi
	done
}

### LO NOTES
### First a connection leaves // client:**** -> server:80			acl_LO_CLIENT()
### Then a connection is received // server:80 <- client:****			acl_LO_SERVER()
### Next server tries to connect back // server:80 -> client:****		acl_LO_SERVER()
### Finally client establishes the connection // client:**** <- server:80	acl_LO_CLIENT()

# For the time being, we need a special function for acl'ing loopback
acl_lo_client()
{
	local ip="$1"
	local port="$2"
	local user_group="$3"
	local protocol="$4"

	local user="${user_group%%:*}"
	local group="${user_group#*:}"

	if [ ! -z $user ]; then
		local user="-m owner --uid-owner $user"
	fi

	if [ ! -z $group ]; then
		local group="-m owner --gid-owner $group"
	fi

	iptables -A OUTPUT -o lo -p $protocol -s $ip -d $ip --dport $port $user $group -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
	iptables -A INPUT  -i lo -p $protocol -d $ip -s $ip --sport $port -m state --state ESTABLISHED,RELATED -j ACCEPT
}

# A server function to prevent reduntant rules
acl_lo_server()
{

	local ip="$1"
	local port="$2"
	local user_group="$3"
	local protocol="$4"

	local user="${user_group%%:*}"
	local group="${user_group#*:}"

	if [ ! -z $user ]; then
		local user="-m owner --uid-owner $user"
	fi

	if [ ! -z $group ]; then
		local group="-m owner --gid-owner $group"
	fi

	iptables -A INPUT  -i lo -p $protocol -d $ip -s $ip --dport $port -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
	iptables -A OUTPUT -o lo -p $protocol -s $ip -d $ip --sport $port $user $group -m state --state ESTABLISHED,RELATED -j ACCEPT
}

acl_lo()
{
	acl_lo_client "$1" "$2" "$3" "$4"
	acl_lo_server "$1" "$2" "$3" "$4"
}

apply()
{
	local filter="$(iptables-save | awk '/\*filter/{flag=1} /COMMIT/{flag=0} flag')"
	local mangle="$(iptables-save | awk '/\*mangle/{flag=1} /COMMIT/{flag=0} flag')"
	local nat="$(iptables-save | awk '/\*nat/{flag=1} /COMMIT/{flag=0} flag')"
	local raw="$(iptables-save | awk '/\*raw/{flag=1} /COMMIT/{flag=0} flag')"

	iptables-restore << _EOF
$filter
$_filter_rules
COMMIT
$mangle
COMMIT
$nat
$_nat_rules
COMMIT
$raw
COMMIT
_EOF

}

save()
{
	# Sysvinit/systemd
	[[ $(which service 2>/dev/null) ]] && service iptables save || \
	# openrc
	[[ $(which rc-service 2>/dev/null) ]] && rc-service iptables save
}
